DROP TABLE FILMORATE_LIKE;

DROP TABLE FILMORATE_FILM_GENRE;

DROP TABLE FILMORATE_GENRE;

DROP TABLE FILMORATE_FILM;

DROP TABLE FILMORATE_MPA_RATING;

DROP TABLE FILMORATE_FRIENDSHIP;

DROP TABLE FILMORATE_FRIENDSHIP_STATUS;

DROP TABLE FILMORATE_USER;