-- CREATE TABLE IF NOT EXISTS "filmorate_friendship_status" (
--   "status_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "status_name" varchar UNIQUE
-- );

INSERT INTO filmorate_friendship_status (status_name)
VALUES ( 'REQUESTED'),
	( 'APPROVED'),
	( 'REJECTED')
ON CONFLICT(status_name) DO NOTHING;

SELECT * FROM filmorate_friendship_status;
