DROP TABLE if exists FILMORATE_LIKE;

DROP TABLE if exists FILMORATE_FILM_GENRE;

DROP TABLE if exists FILMORATE_GENRE;

DROP TABLE if exists FILMORATE_FILM;

DROP TABLE if exists FILMORATE_MPA_RATING;

DROP TABLE if exists FILMORATE_FRIENDSHIP;

DROP TABLE if exists FILMORATE_USER;